---
editor:
  title: 'crwdns64271:0crwdne64271:0'
  mainLogo:
    title: 'crwdns64273:0crwdne64273:0'
    uploader:
      instructions: 'crwdns64275:0crwdne64275:0'
      uploading: 'crwdns64277:0crwdne64277:0'
  iconLogo:
    title: 'crwdns64279:0crwdne64279:0'
    uploader:
      instructions: 'crwdns64281:0crwdne64281:0'
      uploading: 'crwdns64283:0crwdne64283:0'
  favicon:
    title: 'crwdns64285:0crwdne64285:0'
    uploader:
      instructions: 'crwdns64287:0crwdne64287:0'
      uploading: 'crwdns64289:0crwdne64289:0'

