errors:
  disabled: отключенный рабочий процесс или триггер
  handleNotUnique: дескриптор рабочего процесса не уникален
  invalidHandle: Неверный handle
  invalidID: неверный ID
  notAllowedToCreate: не разрешено создавать рабочий процесс
  notAllowedToDelete: не разрешено удалять  рабочий процесс
  notAllowedToExecute: не разрешено выполнять рабочий процесс
  notAllowedToExecuteCorredorStep: не разрешено запускать функцию corredorExec, corredor отключен
  notAllowedToRead: не разрешено читать рабочий процесс
  notAllowedToSearch: не разрешено искать или перечислять рабочий процесс
  notAllowedToUndelete: не разрешено восстанавливать рабочий процесс
  notAllowedToUpdate: не разрешено обновлять рабочий процесс
  notFound: ' рабочий процесс не найден'
  staleData: устаревшие данные
  unknownWorkflowStep: неизвестный шаг рабочего процесса
