configuration: Configuration
edge: Bord
name:
  label: Nom *
  placeholder: Nom de processus
handle:
  label: Identifiant
  placeholder: identifiant unique (a - z, 0 - 9, tiret du bas, tiret)
  invalid-handle-characters: Doit contenir au moins 2 caractères. Ne peut contenir que des lettres, nombres, tirets bas et tirets. Doit se terminer avec une lettre ou un nombre.
description:
  label: Description
  placeholder: Décrivez ce que fait ce processus
target: Cible
tooltip:
  run-workflow: Exécuter processus
  configure-step: Configurer l'étape
run-as:
  label: Exécuter en tant que
  placeholder: Utilisateur qui exécutera le processus
  description: Quand non défini, le processus sera exécuté par l'utilisateur l'ayant déclenché
sub-workflow:
  label: Sous processus
  description: Les sous-processus ne peuvent pas avoir de déclencheurs
