content:
  label: Contenu
  short: Contenu
  configurator:
    ok: Ok
    urlPlaceholder: https://example.tld
continue:
  label: Continuer
  short: Continuer
delay:
  tooltip: Retarde l'exécution du processus
error:
  label: Erreur
  short: Erreur
  tooltip: Génère une erreur et interrompt l'exécution du processus, empêche également l'enregistrement d'éléments avec des déclencheurs 'before'
error-handler:
  tooltip: Continue le processus à partir de cette étape si une erreur est déclenchée
expressions:
  configurator:
    expression: Expression
    expression-placeholder: Expression...
function:
  configurator:
    expression: Expression
    name: Nom
    option-select: Sélectionnez une option
    result: Résultat
    search-workflow: Recherche d'un processus
    type: Type
    type*: Type*
  label: Fonction
  short: Fonction
exec-workflow:
  label: Exécuter Processus
  short: Processus
gateway:
  configurator:
    condition: Condition
termination:
  tooltip: Mettre fin à l'exécution du processus
trigger:
  configurator:
    add: + Ajouter
    failed-fetch-event-types: Échec de la récupération des types d'évènement
    equal: Égal
    not-equal: Différent de
  short: Triggers
  tooltip: Déclenche l'exécution du processus selon la configuration
