errors:
  invalidID: неверный ID
  notAllowedToCreate: не разрешено создавать приложение
  notAllowedToDelete: не разрешено удалять это приложение
  notAllowedToManageFlag: не разрешено управлять флагами для приложений
  notAllowedToManageFlagGlobal: не разрешено управлять глобальными флагами для приложений
  notAllowedToRead: не разрешено читать это приложение
  notAllowedToSearch: не разрешено искать или перечислять приложения
  notAllowedToUndelete: не разрешено восстанавливать это приложение
  notAllowedToUpdate: не разрешено обновлять это приложение
  notFound: Приложение не найдено
