automation: Автоматизация
chart: Диаграммы
configuration: Конфигурация
editPage: Редактировать страницу
help:
  documentation: Документация
  feedback: Обратная связь
  forum: Помощь
  version: 'Версия:'
module: Модули
more: Подробнее
namespace: Пространство имен
noPageTitle: Нет заголовка страницы
page: Страницы
userSettings:
  changePassword: Смена пароля
  loggedInAs: Вы вошли как {{user}}
  logout: Выйти
  profile: Профиль
viewPage: Просмотр страницы
