automation:
  scriptFailed: Не удалось выполнить автоматизацию
chart:
  createFailed: Не удалось создать отчет
  deleteFailed: Не удалось удалить диаграмму
  deleted: Диаграмма удалена
  invalidConfig:
    missingDimensionsField: Поле размеров не определено
    missingDimensionsModifier: Модификатор размеров не определен
    missingMetricsAggregate: Совокупность показателей не определена
    missingMetricsField: Показатели поля не определены
    missingMetricsType: Показатели диаграммы не определены
    missingModuleID: Модуль не определен
    missingReports: Отчеты не определены
  loadFailed: Не удалось загрузить диаграмму
  optionsBuildFailed: Не удалось построить параметры диаграммы
  unsupportedRenderer: Неподдерживаемый визуализатор
color:
  RGBA:
    invalid: Недопустимый цветовой формат RGBA
field:
  missingRequired: Отсутствует значение в обязательном поле
  unknownFieldKind: 'Ошибка: Неизвестный тип поля "{{kind}}", компонент просмотра не найден.'
  unsupportedKind: Неподдерживаемый тип поля {{kind}}
field-datetime:
  valueNotFuture: Прошлое значение только в будущем поле
  valueNotPast: Будущее значение только в прошлом поле
general:
  composeAccessNotAllowed: Нет доступа к Compose
  error: Ошибка
  success: Успешно
  warning: Предупреждение
  import:
    failed: Не удалось импортировать
    readingError: Ошибка чтения файла
    successful: Импорт успешно завершен
    typeMissmatch: 'Ошибка импорта: попытка импортировать объект типа "{{type1}}" в список объектов типа "{{type2}}"'
list:
  load:
    error: Не удалось загрузить ресурс
module:
  deleteFailed: Не удалось удалить модуль
  deleted: Модуль удален
  saveFailed: Не удалось сохранить этот модуль
  saved: Модуль сохранен
  columns:
    saved: Столбцы сохранены
    saveFailed: Не удалось сохранить столбцы
  recordPage:
    createFailed: Не удалось создать страницу записи модуля
namespace:
  application:
    createFailed: Не удалось создать приложение пространства имен
    fetchFailed: Не удалось получить приложение пространства имен
    saveFailed: Не удалось сохранить приложение пространства имен
  assetUploadFailed: Не удалось загрузить прикрепленные ресурсы
  createFailed: Не удалось создать пространство имен
  deleteFailed: Не удалось удалить пространство имен
  disabled: Пространство имен отключено — перенаправление
  saveFailed: Не удалось сохранить пространство имен
  saved: Пространство имен сохранено
  cloneFailed: Не удалось клонировать пространство имен
  imported: Пространство имен импортировано
  importFailed: Не удалось импортировать пространство имен
page:
  createFailed: Не удалось создать страницу
  deleteFailed: Не удалось удалить страницу
  noPages: Страницы не найдены
  saveFailed: Не удалось сохранить страницу
  saveFailedRequired: Не удалось сохранить эту страницу, должны присутствовать все обязательные поля модуля
  saved: Страница сохранена
record:
  createFailed: Не удалось создать запись
  createSuccess: Запись создана
  updateFailed: Не удалось изменить запись
  updateSuccess: Обновить запись
  deleteFailed: Не удалось удалить запись
  deleteBulkFailed: Не удалось удалить выбранные записи
  deleteBulkSuccess: Успешно удалены выбранные записи
  invalidOwnerVar: Не может использовать переменную ${ownerID} на страницах, не являющихся variable
  invalidRecordVar: Не может использовать переменную ${record...} на страницах, не являющихся variable
  listLoadFailed: Не удалось загрузить список записей
  loadFailed: Не удалось загрузить запись
  moduleMismatch: Несовместимый модуль, несоответствие модулей
  moduleNotDefined: Модуль записи не определен
  moduleOrPageNotSet: 'Ошибка блока RecordList: не задан параметр модуля или страницы'
  unexpectedInput: Неожиданный ввод для свойства values, должен быть массивом с парами объектов "name-value"
  unexpectedValue: Неожиданное значение для модуля записи ({{type}})
