template:
  title: 安全
  password:
    title: 密码
    change-link: 更改密码
  mfa:
    title: 多因素身份验证
    totp:
      title: TOTP（基于时间的移动应用一次性密码）
      enforced: 已启用
      configure: 配置
      enable: 启用
      disable: 停用
      enabled: 已启用基于时间的一次性密码
      disabled: 已停用
    email:
      title: 电子邮件 OTP（发送到邮箱的一次性密码）
      enforced: 已启用
      enable: 启用
      disable: 停用
      enabled: 已启用电子邮件双因素身份验证
      disabled: 已停用电子邮件双因素身份验证
    all-disabled: 目前所有多因素身份验证方法均已停用。请联系管理员启用。
