template:
  title: Segurança
  password:
    title: Senha
    change-link: Alterar sua senha
  mfa:
    title: Autenticação de múltiplos fatores
    totp:
      title: Segurança adicional com aplicativo móvel (senha baseada em tempo e de uso único)
      enforced: Configurado e obrigatório ao entrar.
      disabled: Atualmente desabilitado.
      configure: Configurar
      disable: Desabilitar
    email:
      title: Segurança adicional com geração de código temporário por e-mail
      enforced: Habilitado e obrigatório ao logar-se.
      disabled: Atualmente desabilitado.
      enable: Configurar
      disable: Desabilitar
    all-disabled: Todos os métodos de autenticação de múltiplos fatores estão desabilitados. Contate o administrador para habilitá-los.
alerts:
  topt-disabled: Autenticação de 2 fatores com TOTP desabilitado
