errors:
  invalidID: ID invalide
  notAllowedToCreate: non autorisé à créer des applications
  notAllowedToDelete: non autorisé à supprimer cette application
  notAllowedToRead: non autorisé à lire cette application
  notAllowedToSearch: non autorisé pour rechercher ou lister les applications
  notAllowedToUndelete: non autorisé à annuler la suppression de cette application
  notAllowedToUpdate: non autorisé à mettre à jour cette application
  notFound: application introuvable
