errors:
  notAllowedToRead: non autorisé pour lire ce paramètre
  notAllowedToManage: non autorisé à gérer ce paramètre
  invalidPasswordMinLength: la longueur minimale dans la contrainte de mot de passe doit être d'au moins 8 caractères
  invalidPasswordMinUpperCase: le nombre minimum de majuscules dans la contrainte de mot de passe ne doit pas être un nombre négatif
  invalidPasswordMinLowerCase: le nombre minimum de minuscules dans la contrainte de mot de passe ne doit pas être un nombre négatif
  invalidPasswordMinNumCount: le nombre minimum de nombre dans la contrainte de mot de passe ne doit pas être un nombre négatif
  invalidPasswordMinSpecialCharCount: le nombre minimum de caractères spéciaux dans la contrainte de mot de passe ne doit pas être un nombre négatif
