errors:
  disabled: deshabilitado el workflow o trigger
  handleNotUnique: el identificador del workflow no es único
  invalidHandle: identificador inválido
  invalidID: ID inválido
  notAllowedToCreate: no tiene permitido crear workflows
  notAllowedToDelete: no tiene permitido eliminar este workflow
  notAllowedToExecute: no tiene permitido ejecutar este workflow
  notAllowedToExecuteCorredorStep: no tiene permitido ejecutar la función corredorExec, corredor está deshabilitado
  notAllowedToRead: no tiene permitido leer este workflow
  notAllowedToSearch: no tiene permitido buscar o listar workflows
  notAllowedToUndelete: no tiene permitido deshacer la eliminación de este workflow
  notAllowedToUpdate: no tiene permitido actualizar este workflow
  notFound: workflow no encontrado
  unknownWorkflowStep: paso del workflow desconocido
