template:
  title: Безопасность
  password:
    title: Пароль
    change-link: Смените ваш пароль
  mfa:
    title: Multi-factor authentication
    totp:
      title: Дополнительная безопасность с мобильным приложением (одноразовый пароль на основе времени)
      enforced: Настроен и требуется при входе в систему
      configure: Настроить
      enable: Включено
      disable: Отключен
    email:
      title: Дополнительная безопасность с одноразовым паролем по электронной почте
      enforced: Включено и требуется при входе в систему
      enable: Включено
      disable: Отключен
    all-disabled: Все методы MFA в настоящее время отключены. Попросите вашего администратора включить их.
