template:
  title: Безопасность
  password:
    title: Пароль
    change-link: Смените ваш пароль
  mfa:
    title: Multi-factor authentication
    totp:
      configure: Настроить
      enable: Включено
      disable: Отключен
    email:
      enable: Включено
      disable: Отключен
    all-disabled: Все методы MFA в настоящее время отключены. Попросите вашего администратора включить их.
