colorLabel: '{{count}} ألوان'
colorScheme:
  label: نظام الألوان
  placeholder: اختر نظام ألوان
  custom:
    modal:
      name:
        label: اسم
configure:
  reportsLabel: التقارير
general:
  label:
    title: وصف
    add: أضف
    permissions: الصلاحيات
  value: قيمة
edit:
  dimension:
    calculateLabelCount: احسب عدد الملصقات التي يمكن عرضها
    defaultValueFootnote: استخدم هذه القيمة لقيم الأبعاد المفقودة
    defaultValueLabel: القيم الافتراضية
    fieldLabel: حقل *
    fieldPlaceholder: حدد حقل البعد
    function:
      placeholder: حدد معدل الأبعاد (حجم المحموعة)
      date: تاريخ
      label: دالة
      month: شهر
      quarter: ربع
      week: اسبوع
      year: سنة
    gaugeSteps: خطوات
    label: ابعاد
    skipMissingValues: تخطي القيم المفقودة
    optionsPicker:
      searchPlaceholder: اكتب هنا للبحث بين الخيارات المحددة
      availableItems: الخيارات المتوفرة
      selectAllItems: تحديد الكل
      selectedItems: اختيار خيار
      unselectAllItems: الغاء تحديد الكل
      noItemsFound: لم يتم العثور على خيارات
  filter:
    customize: تخصيص عامل التصفية
    label: مرشح
    placeholder: الحقل 1 = 1 و الحقل 2 = 232
    recordsCreatedLastMonth: السجلات التي تم إنشاؤها الشهر الماضي
    recordsCreatedLastQuarter: السجلات التي تم إنشاؤها في الربع الأخير
    recordsCreatedLastYear: السجلات التي تم إنشاؤها العام الماضي
    recordsCreatedThisMonth: السجلات التي تم إنشاؤها هذا الشهر
    recordsCreatedThisQuarter: السجلات التي تم إنشاؤها هذا الربع
    recordsCreatedThisYear: السجلات التي تم إنشاؤها هذا العام
  loadData: تحميل البيانات
  metric:
    title: مقياس
    add: أضف مقياس
    fieldLabel: حقل *
    fieldPlaceholder: حدد حقل القياس
    fillArea: املأ المنطقة أسفل الخط
    function:
      avg: متوسط
      label: دالة
      max: اعلى
      min: ادنى
      placeholder: حدد دالة التجميع المتري
      std: STD
      sum: SUM
    fx:
      description: n - current dataset value, m - previous dataset value
      label: وظيفة المعالجة اللاحقة
    lineStyle:
      default: افتراضي
    gaugeColor: اللون
    label: مقياس
    labelColor: لون التسمية
    labelLabel: وصف
    labelPlaceholder: المجموع
    legend:
      bottom: الأسفل
      left: يسار
      positionPlaceholder: مكان الدليل
      right: يمين
      top: اعلى
    lineTension:
      curvy: انحناءات كبيرة
      label: توتر الخط
      medium: انحناءات متوسطة
      placeholder: توتر الخط
      slight: انحناءات صغيرة
      straight: خطوط مستقيمة
    output:
      bar: عمود
      doughnut: دونت
      line: خطي
      pie: دائري
      placeholder: حدد الإخراج المتري
    relative: إظهار القيمة النسبية
    relativePrecision: 'دقة:'
  module:
    label: موديول *
    placeholder: اختر موديول
  title: منشئ الرسم البياني
  unconfiguredReport: تقرير غير مكون
  yAxis:
    axisOnRight: ضع المحور على الجانب الأيمن
    axisScaleFromZero: ابدأ دائمًا بمقياس المحور عند الصفر
    label: محور ص
    labelLabel: اسم المحور
    labelPosition:
      bottom: انهاء
    horizontal:
      label: افقي
    logarithmicScale: وزن لوغارثمي
    maxLabel: اقصى قيمة
    maxPlaceholder: اقصى قيمة
    minLabel: اقل قيمة
    minPlaceholder: اقل قيمة
  additionalConfig:
    legend:
      show: عرض الدليل
      orientation:
        horizontal: افقي
        vertical: عمودي
      align:
        left: يسار
        right: يمين
      position:
        top: اعلى
        right: يمين
        bottom: الأسفل
        left: يسار
    offset:
      label: عوض
      position:
        top: اعلى
        right: يمين
        bottom: الأسفل
        left: يسار
  toolbox:
    timeline:
      options:
        none: لايوجد
        x: محور س
        y: محور ص
  formatting:
    format:
      label: شكل
    prefix:
      label: بادئة
    suffix:
      label: لاحقة
    presetFormats:
      label: شكل
      options:
        custom: مخصص
import: 'استيراد المخططات:'
newLabel: 'إنشاء مخطط جديد:'
name: اسم الرسم البياني *
handle: المعرف
notification:
  loadFailed: تعذر تحميل المخطط
  saveFailed: لا يمكن حفظ هذا الرسم البياني
  saved: تم حفظ الرسم البياني
  deleteFailed: تعذر حذف هذا الرسم البياني
  deleted: تم حذف الرسم البياني
title: قائمة التقارير
undefined: غير معرف
