automation: أتمتة
chart: الرسوم البيانية
configuration: اعدادات
editPage: تعديل الصفحة
help:
  documentation: المراجع
  feedback: ارسال افادة
  forum: مساعدة
  version: 'النسخة:'
module: الموديولز
more: مزيد
namespace: Namespaces
noPageTitle: لايوجد عنوان
page: الصفحات
userSettings:
  changePassword: تغيير كلمة المرور
  loggedInAs: مسجل كـ {{user}}
  logout: تسجيل خروج
  profile: الملف الشخصي
viewPage: عرض الصفحة
