automation:
  scriptFailed: تعذر تنفيذ الأتمتة
chart:
  createFailed: تعذر إنشاء مخطط
  deleteFailed: تعذر حذف هذا الرسم البياني
  deleted: تم حذف الرسم البياني
  invalidConfig:
    missingDimensionsField: لم يتم تعريف حقل الأبعاد
    missingDimensionsModifier: لم يتم تعريف معدل الأبعاد
    missingMetricsAggregate: لم يتم تعريف إجمالي المقاييس
    missingMetricsField: لم يتم تحديد حقل المقاييس
    missingMetricsType: لم يتم تحديد نوع مخطط المقاييس
    missingModuleID: الوحدة النمطية غير محددة
    missingReports: لم يتم تعريف التقارير
  loadFailed: تعذر تحميل المخطط
  optionsBuildFailed: لا يمكن بناء خيارات الرسم البياني
  unsupportedRenderer: عارض غير مدعوم
color:
  RGBA:
    invalid: تنسيق ألوان RGBA غير صالح
field:
  missingRequired: القيمة مفقودة في الحقل المطلوب
  unknownFieldKind: 'خطأ: نوع الحقل غير معروف "{{kind}}" ، لم يتم العثور على مكون عارض.'
  unsupportedKind: نوع الحقل غير مدعوم {{kind}}
field-datetime:
  valueNotFuture: القيمة السابقة في حقل المستقبل فقط
  valueNotPast: القيمة المستقبلية للحقل الماضي فقط
general:
  composeAccessNotAllowed: غير مسموح له بالوصول إلى "إنشاء"
  error: خطأ
  success: ناجح
  warning: تنبيه
  info: ملاحظة
  import:
    failed: فشل الاستيراد
    readingError: خطأ في قراءة الملف
    successful: نجح الاستيراد
    typeMissmatch: 'خطأ في الاستيراد: محاولة استيراد كائن من النوع "{{type1}}" إلى قائمة كائنات من النوع "{{type2}}"'
list:
  load:
    error: فشل تحميل قائمة الموارد
module:
  deleteFailed: تعذر حذف هذه الوحدة
  deleted: تم حذف الوحدة النمطية
  saveFailed: تعذر حفظ هذه الوحدة
  saved: تم حفظ الوحدة
  columns:
    saved: تم حفظ الأعمدة
    saveFailed: تعذر حفظ الأعمدة
  recordPage:
    createFailed: تعذر إنشاء صفحة تسجيل الوحدة النمطية
namespace:
  application:
    createFailed: تعذر إنشاء تطبيق مساحة الاسم
    fetchFailed: تعذر إنشاء تطبيق مساحة الاسم
    saveFailed: تعذر حفظ تطبيق مساحة الاسم
  assetUploadFailed: تعذر تحميل الأصول المرفقة
  createFailed: تعذر إنشاء مساحة الاسم
  deleteFailed: تعذر حذف مساحة الاسم هذه
  disabled: تم تعطيل مساحة الاسم - إعادة التوجيه
  saveFailed: تعذر حفظ مساحة الاسم هذه
  saved: تم حفظ مساحة الاسم
  cloneFailed: تعذر استنساخ مساحة الاسم هذه
  imported: تم استيراد مساحة الاسم
  importFailed: فشل استيراد Namespace
page:
  createFailed: تعذر إنشاء صفحة
  deleteFailed: لا يمكن حذف هذه الصفحة
  noPages: لا توجد صفحات
  saveFailed: لا يمكن حفظ هذه الصفحة
  saveFailedRequired: تعذر حفظ هذه الصفحة ، يجب أن تكون جميع حقول الوحدة المطلوبة موجودة
  saved: تم حفظ الصفحة
record:
  createFailed: تعذر إنشاء السجل
  createSuccess: تم انشاء السجل
  updateFailed: تعذر تحديث السجل
  updateSuccess: تم تحديث السجل
  deleteFailed: تعذر حذف السجل
  deleteBulkFailed: تعذر حذف السجلات المحددة
  deleteBulkSuccess: تم حذف السجلات المحددة بنجاح
  invalidOwnerVar: لا يمكن استخدام متغير ${ownerID} في الصفحات غير المسجلة
  invalidRecordVar: لا يمكن استخدام متغير ${record...} في الصفحات غير المسجلة
  listLoadFailed: تعذر تحميل قائمة السجلات
  loadFailed: تعذر تحميل السجل
  moduleMismatch: الوحدة غير متوافقة ، الوحدة غير متطابقة
  moduleNotDefined: وحدة التسجيل غير محددة
  moduleOrPageNotSet: 'خطأ في حظر قائمة السجل: لم يتم تعيين خيار الوحدة النمطية أو الصفحة'
  unexpectedInput: إدخال غير متوقع لخاصية القيم ، يجب أن يكون مصفوفة تحتوي على أزواج كائن من الاسم والقيمة
  unexpectedValue: قيمة غير متوقعة لوحدة السجل ({{type}})
report:
  listFetchFailed: فشل في احضار التقارير
  fetchFailed: فشل في احضار تقرير
  runFailed: فشل في تشغيل تقرير
