editor:
  title: Configurações de sistema
  auth:
    title: Autenticação
    url: URL
    internal:
      title: Interna
      enabled: Autenticação interna ativada
      password-reset:
        enabled: Redefinição de senha ativada
      password-constraints:
        title: Restrições de senha
        ignored-security: O sistema está configurado para ignorar as restrições de segurança de senha que são inseguras em implementações de produção. Se esta for uma implantação de produção, entre em contato com seu administrador para atualizar a configuração do sistema (a variável AUTH_PASSWORD_SECURITY .env).
        min-length: Comprimento mínimo
        min-length-description: Deve ter pelo menos 8 caracteres
        min-num-count: Número mínimo de números
        min-num-count-description: A senha deve incluir a quantidade de números especificado (desativado se definido como 0)
        min-special-count: Número mínimo de caracteres especiais
        min-special-count-description: A senha deve incluir a quantidade de caracteres especiais especificado (desativado se definido como 0)
        min-upper-case-length: Número mínimo de caracteres maiúsculos
        min-upper-case-description: A senha deve incluir a quantidade de caracteres maiúsculos (desativado se definido como 0)
        min-lower-case-length: Número mínimo de caracteres minúsculos
        min-lower-case-description: A senha deve incluir a quantidade de caracteres minúsculos (desativado se definido como 0)
      signup:
        email-confirmation-required: Confirmação de cadastro por e-mail obrigatória
        enabled: Cadastro habilitado
        split-credentials-check:
          description: 'Divida o login em duas etapas, colete a entrada de e-mail primeiro e mostre a entrada para a senha na segunda tela. Encaminhe automaticamente o usuário para o provedor de identidade externo quando o usuário não tiver sua senha definida e houver apenas um IdP presente'
          label: Ativar verificação de credenciais divididas
      profile-avatar:
        enabled: Avatar de perfil habilitado
      send-user-invite-email:
        title: Convidar email
        enabled: Enviar email de convite na criação de usuário
        description: Quando ativada, essa configuração envia um email de convite para um usuário recém-criado por meio da CLI
        expires:
          label: Valido para
          description: Por quanto tempo o token de convite será válido antes de expirar
    mail:
      title: Email do remetente do e-mail de autenticação
      from-address: Endereço do remetente
      from-name: Nome do remetente
      validate-email: Por favor insira o endereço de e-mail válido
    mfa:
      title: Autenticação multifator
      TOTP:
        enabled: Ativar TOTP (senha de uso único baseada em tempo via aplicativo móvel)
        enforced: Exigir que todos os usuários usem TOTP
        issuer:
          description: O nome do emissor será enviado ao aplicativo autenticador quando o usuário o configurar
          label: Emissor
      emailOTP:
        enabled: Ligar email OTP (senha de uso único enviado ao email)
        enforced: Exigir que todos os usuários usem email OTP
        expires:
          description: Por quanto tempo a senha será válida antes de expirar
          label: Valido para
    auto-logout:
      title: Logout automático
      enabled:
        label: Habilitado
        description: Desconectar automaticamente os usuários após um determinado período de inatividade
      timeout:
        label: Tempo de expiração
        description: O período de inatividade em segundos antes de um usuário ser desconectado
  external:
    title: Provedores de autenticação externa
    enabled: Ativar autenticação externa
    table:
      header:
        enabled: Habilitado
        provider: Fornecedor
        info: Emissor, ID do cliente
    standard:
      enabled: Habilitado
      apiAccess: Acesso à API
      clientKey: Chave do cliente
      clientSecret: Segredo
    oidc:
      add: Adicionar um provedor OIDC
      enabled: Habilitado
      handle: Identificador
      title: Conexão com OpenID
      issuer: URL do emissor OIDC
      issuerHint: Onde encontrar a /.well-known/openid-configuration (sem a parte /.well-known/openid-configuration)
      clientKey: Chave do cliente
      clientSecret: Segredo
      scope: Alcance
      scopePlaceholder: Listar os valores de escopo OAuth compatíveis
      scopeHint: Usar string delimitada por espaço
    saml:
      enabled: Habilitado
      title: SAML
      requests:
        title: Requisições
        sign-requests: Solicitações de assinatura
        sign-method: Método de assinatura
        binding: Vinculativo
        binding-redirect: Redirecionamento HTTP
        binding-post: HTTP POST
      cert:
        public: Chave pública
        private: Chave privada
      name: Nome
      certificate: Certificado
      idp:
        title: Provedor de identidade
        ident-handle: Campo do identificador
        ident-identifier: Campo identificador
        ident-name: Campo de nome
        url: URL
      desc:
        name: Nome IdP utilizado na tela de login (Entrar como <name>)
        cert:
          public: O conteúdo será minimizado
          private: O conteúdo será minimizado
        requests:
          sign-requests: Assinar AuthNRequest e afirmação
          sign-method: Método a ser usado em solicitações assinadas
          binding: O tipo de ligação HTTP a ser usado em AuthNRequest, o padrão é HTTP Redirect (GET)
        idp:
          url: Localização dos metadados do IdP
          ident-handle: Nome do campo IdP usado para preencher o identificador de usuário ou apelido do Corteza
          ident-identifier: Nome do campo IdP usado para preencher e corresponder o e-mail do usuário do Corteza
          ident-name: Nome do campo IdP usado para preencher o nome completo do usuário Corteza
    security:
      title: Segurança
      prohibited-roles:
        description: As funções desta lista serão removidas do contexto de segurança ao autenticar com este provedor
        label: Funções proibidas
      forced-roles:
        description: As funções desta lista serão sempre adicionadas ao contexto de segurança ao autenticar com este provedor
        label: Funções forçadas
      permitted-roles:
        description: Somente as funções nesta lista serão adicionadas ao contexto de segurança quando autenticadas com este provedor
        label: Funções permitidas
  bgScreen:
    title: Tela de fundo de autenticação
    image:
      uploader:
        label: Imagem de fundo
      editor:
        label: CSS customizado
