editor:
  title: Configurações da interface do usuário
  corteza-studio:
    mainLogo:
      title: Logotipo principal
      uploader:
        instructions: Clique ou solte o logotipo principal aqui para fazer o upload
        uploading: Enviando logotipo principal
    iconLogo:
      title: Logotipo do ícone
      uploader:
        instructions: Clique ou solte a imagem do logotipo do ícone aqui para fazer o upload
        uploading: Enviando o logotipo do ícone
    label:
      default: Predefinição
    tabs:
      general: Em geral
      light: Luz
      dark: Escuro
    theme:
      variables:
        primary:
          label: Primário
        secondary:
          label: Secundário
        success:
          label: Sucesso
        warning:
          label: Aviso
        danger:
          label: Perigo
        light:
          label: Luz
  topbar:
    general: Em geral
    help:
      title: Ajuda
    profile:
      title: Perfil
    links:
      handle: Nome
      url: URL
