errors:
  handleNotUnique: handle  не уникален
  invalidHandle: Неверный handle
  invalidID: неверный ID
  invalidNamespaceID: неверное или отсутствующее пространство имен ID
  moduleNotFound: module does not exist
  namespaceNotFound: namespace does not exist
  notAllowedToCreate: не разрешено создавать отчет
  notAllowedToDelete: не разрешено удалять этот отчет
  notAllowedToRead: не разрешено читать этот отчет
  notAllowedToReadNamespace: не разрешено читать это пространство имен
  notAllowedToSearch: не разрешено искать или перечислять отчеты
  notAllowedToUndelete: не разрешено восстанавливать этот отчет
  notAllowedToUpdate: не разрешено обновлять этот отчет
  notFound: chart does not exist
  staleData: устаревшие данные
