content:
  label: Content
  short: Content
  configurator:
    ok: Да
    urlPlaceholder: https://example.tld
continue:
  label: Продолжить
  short: Продолжить
error:
  label: Ошибка
  short: Ошибка
expressions:
  configurator:
    expression: Выражение
    expression-placeholder: Выражение...
function:
  configurator:
    expression: Выражение
    name: Имя
    result: Результат
    results: Результат
    type: Тип
    type*: Тип*
  label: Функция
  short: Функция
iterator:
  label: Итератор
  short: Итератор
trigger:
  configurator:
    add: + Добавить
    constraints: Ограничения
    event*: Событие*
    equal: Равно
    not-equal: Не равно
    operator: Оператор
    resource: Ресурс
    resource*: Ресурс*
