automation:
  add: Ajouter script
  edit:
    asyncLabel: Exécuter ce script de manière asynchrone
    codeTabLabel: Code
    criticalLabel: Script critique
    delete: Supprimer script
    enabledLabel: Activé
    mailAutomationTriggers:
      addMatcher: Ajouter condition
      addTrigger: Ajouter déclencheur
      delete: Supprimer déclencheur
      deleteTrigger: Supprimer
      enable: Activer déclencheur
      matchAll: Doit correspondre à toutes les conditions
      matcher:
        fields:
          bcc: CCI
          cc: CC
          from: Depuis
          replyTo: Répondre à
          subject: Sujet
          to: A
        match: Valeur à faire correspondre
        operators:
          equal-ci: Correspondance complète
          placeholder: Opérateur
          regex: Expression régulière
          user: Utilisateur existant
      tabLabel: Déclencheurs courriel
    nameLabel: Nom
    namePlaceholder: Nom du script d'automatisation
    runAsCurrentUser: Exécuter en tant que "{{ user }}"
    runAsHelp: Exécuteur du script
    securityLabel: Sécurité
    settingsTabLabel: Paramètres
    timeoutPlaceholder: "1500"
    title: Script d'automatisation
    userPickerPlaceholder: Sélectionnez utilisateur
  import: Importer script(s) d'automatisation
  list:
    column:
      label:
        async: Asynchrone
        critical: Critique
        enabled: Activé
        runAs: Exécuter en tant que
        runInUA: Dans le navigateur
    unnamed: (Script sans nom)
  manage-id-permissions: Gérer les permissions pour ce script
  manage-wc-permissions: Gérer les permissions pour tous les scripts
  newPlaceholder: Nom du script
  testing:
    load: Charger
    resultsHeadline: 'Résultats :'
    testInBrowser: Tester dans Navigateur
    testInCorredor: Tester dans Corredor
  title: Liste de scripts d'automatisme
general:
  notFound: 'Introuvable'
  loading: Chargement
  label:
    "no": "Non"
    submit: Envoyer
    "yes": "Oui"
  logout: Se déconnecter
  noAccess: Vous n'avez pas les permissions pour accéder au panneau d'administration
  pagination:
    next: Suivant
    prev: Précédent
    showing: '{{from}} - {{to}} sur {{count}} {{data}}'
    single_one: '1 {{data}}'
    single_other: '{{count}} {{data}}'
navigation:
  appMenu: Menu
  adminPanel: Panneau d'administration
  automation: Automatisme
  chart: Graphiques
  configuration: Configuration
  help:
    documentation: Documentation
    feedback: Envoyer un retour
    forum: Aide
    version: 'Version :'
  module: Modules
  more: Plus
  namespace: Namespaces
  noPageTitle: Pas de titre de page
  page: Pages
  publicPages: Pages publiques
  userSettings:
    changePassword: Changer mot de passe
    loggedInAs: Connecté en tant que {{user}}
    logout: Se déconnecter
    profile: Profil
    theme: Thème
picker:
  role:
    placeholder: Commencez à taper pour rechercher des rôles
  member:
    placeholder: Commencez à taper pour rechercher des rôles
