dashboard: Tableau de bord
system:
  group: Système
  items:
    users: Utilisateurs
    actionlog: Journaux d'action
    apigw: Passerelle d'intégration
    applications: Applications
    authclients: Clients d'authentification
    connections: Connexions
    code-snippets: Extraits de code
    sensitivityLevel: Niveaux de sensibilité
    permissions: Permissions
    queues: Files de messages
    roles: Rôles
    settings: Paramètres d'authentification
    email: Paramètres de courriel
    stats: Statistiques
    templates: Modèles
compose:
  group: Compose
  items:
    automation: Automatisme
    permissions: Permissions
    settings: Paramètres
automation:
  group: Automatisme
  items:
    permissions: Permissions
    scripts: Scripts Corredor 
    sessions: Sessions
    workflows: Processus
federation:
  group: Fédération
  items:
    nodes: Nœuds
    permissions: Permissions
ui:
  group: Interface utilisateur
  items:
    settings: Paramètres
