editor:
  auth:
    url: URL
    internal:
      password-constraints:
        min-num-count: Nombre minimum de chiffres
        min-num-count-description: Le mot de passe doit contenir le nombre de chiffres spécifié (désactivé si défini à 0)
      send-user-invite-email:
        expires:
          description: Durée de validité du jeton d'invitation avant expiration
    mail:
      validate-email: Merci d'entrer un courriel valide
    mfa:
      title: Authentification multi-facteurs
      TOTP:
        issuer:
          description: Le nom d'émetteur sera transmis à l'application d'authentification à la configuration utilisateur
      emailOTP:
        expires:
          description: Durée de validité du mot de passe avant expiration
    auto-logout:
      enabled:
        label: Activé
  external:
    table:
      header:
        enabled: Activé
    standard:
      enabled: Activé
    oidc:
      enabled: Activé
      handle: Identifiant
      scopePlaceholder: List out supported OAuth scope values, use space delimited string
    saml:
      enabled: Activé
      name: Nom
      idp:
        url: URL
    security:
      title: Sécurité
      forced-roles:
        label: Forced roles ({{count}})
      permitted-roles:
        label: Permitted roles ({{count}})
