editor:
  info:
    createdAt: Créer à
    createdBy: Créer par
    delete: Supprimer
    deletedAt: Supprimer à
    enabled: Activé
    name: Nom *
    undelete: Annuler suppression
    updatedAt: Mis à jour à
  new: Nouvelle Application
  permissions: Permissions
  unify:
    config:
      label: Configuration
    logo:
      label: Logo
      reset: Réinitialiser
    name:
      label: Nom
    title: Sélecteur d'application
    url:
      label: URL
list:
  columns:
    enabled: Activé
    name: Nom
  export: Exporter
  new: Nouvelle Application
  permissions: Permissions
  delete: Supprimer
  undelete: Annuler suppression
