colorLabel: '{{count}} Farben'
colorScheme:
  custom:
    modal:
      name:
        label: Name
configure:
  reportsLabel: Datensätze
general:
  label:
    title: Label
    add: Hinzufügen
    count: Anzahl
    permissions: Berechtigungen
  value: Wert
edit:
  dimension:
    defaultValueLabel: Standard Wert
    fieldLabel: Field
    function:
      placeholder: Dimensionsmodifikator auswählen (Eimergröße)
      none: (no grouping / buckets)
      date: DATE
      label: Funktion
      month: MONTH
      quarter: QUARTER
      week: WEEK
      year: YEAR
    label: Dimensions (datetime & select fields)
    optionsPicker:
      selectAllItems: Alle auswählen
      unselectAllItems: Alle abwählen
  filter:
    label: Filters
    footnote: Simplified SQL condition (WHERE ...) syntax is supported. Variables like {{0}}, {{1}} and {{2}} are evaluated (when available)
    placeholder: feld1 = 1 AND feld2 = 232
    noFilter: (no filter)
  metric:
    title: Metrics (numeric fields)
    fieldLabel: Field
    fixTooltips: Always show tooltips
    function:
      label: Funktion
    label: Metrisch
    labelLabel: Label
    labelPlaceholder: Gesamt
    legend:
      bottom: Unten
      left: Links
      positionPlaceholder: Position der Legende
      right: Rechts
      top: Oben
    output:
      bar: Balken
      label: Output
      line: Linie
      pie: Kuchen
      placeholder: Metrische Ausgabe auswählen
    relative: Relativen Wert anzeigen
    relativePrecision: 'Genauigkeit:'
  module:
    label: Module name *
    placeholder: Modul auswählen
  yAxis:
    labelPosition:
      bottom: Ende
  additionalConfig:
    legend:
      align:
        left: Links
        right: Rechts
      position:
        top: Oben
        right: Rechts
        bottom: Unten
        left: Links
    offset:
      position:
        top: Oben
        right: Rechts
        bottom: Unten
        left: Links
  toolbox:
    timeline:
      options:
        none: Kein
  formatting:
    format:
      label: Format
    prefix:
      label: Präfix
    suffix:
      label: Suffix
    presetFormats:
      label: Format
      options:
        custom: Benutzerdefiniert
handle: Name
notification:
  loadFailed: Diagramm konnte nicht geladen werden
  saveFailed: Dieses Diagramm konnte nicht gespeichert werden
  saved: Diagramm gespeichert
  deleteFailed: Dieses Diagramm konnte nicht gelöscht werden
  deleted: Diagramm gelöscht
