automation: Automatisierung
chart: Diagramme
configuration: Konfiguration
editPage: Seite Bearbeiten
help:
  documentation: Dokumentation
  feedback: Feedback senden
  forum: Hilfe
  version: 'Version:'
module: Module
more: Mehr
namespace: Namensräume
noPageTitle: Kein Seitentitel
page: Seiten
userSettings:
  changePassword: Passwort ändern
  loggedInAs: Angemeldet als {{user}}
  logout: Abmelden
  profile: Profil
viewPage: Seite anzeigen
