errors:
  handleNotUnique: l'identifiant n'est pas unique
  invalidHandle: identifiant invalide
  invalidID: ID invalide
  invalidNamespaceID: ID de namespace invalide ou manquant
  moduleNotFound: ce module n'existe pas
  namespaceNotFound: ce namespace n'existe pas
  notAllowedToCreate: non autorisé à créer des graphiques
  notAllowedToDelete: non autorisé à supprimer ce graphique
  notAllowedToRead: non autorisé à lire ce graphique
  notAllowedToReadNamespace: non autorisé à lire ce namespace
  notAllowedToSearch: non autorisé pour rechercher ou lister les graphiques
  notAllowedToUndelete: non autorisé à annuler la suppression de ce graphique
  notAllowedToUpdate: non autorisé à mettre à jour ce graphique
  notFound: ce graphique n'existe pas
  staleData: données obsolètes
