template:
  title: Seguridad
  password:
    title: Contraseña
    change-link: Cambia tu contraseña
  mfa:
    title: Autenticación multi-factor
    totp:
      configure: Configurar
      disable: Deshabilitar
    email:
      disable: Deshabilitar
    all-disabled: Todos los métodos de autenticación multi-factor están deshabilitados. Pregunta a tu administrador para habilitarlos.
