errors:
  notAllowedToRead: not allowed to read this setting
  notAllowedToManage: not allowed to manage this setting
  invalidPasswordMinLength: password constraint minimum length should be at least 8 characters
  invalidPasswordMinNumCount: password constraint minimum number count should not be a negative number
  invalidPasswordMinSpecialCharCount: password constraint minimum special character count should not be a negative number
