configuration: اعدادات
edge: الحد
name:
  label: اسم *
handle:
  label: المعرف
  placeholder: المعرف (a - z, 0 - 9, _, -)
description:
  label: وصف
target: الهدف
run-as:
  label: تشغيل كـ
  description: عند عدم التعيين بشكل صريح ، سيتم تنفيذ سير العمل بواسطة المستخدم الذي استدعاه
