adminPanel: Painel de administração
automation: Automação
chart: Gráficos
configuration: Configuração
help:
  documentation: Documentação
  feedback: Enviar comentário
  forum: Ajuda
  version: 'Versão:'
module: Módulos
more: Mais
namespace: Namespaces
noPageTitle: Sem título de página
page: Páginas
publicPages: Páginas públicas
userSettings:
  changePassword: Mudar senha
  loggedInAs: Conectado como {{user}}
  logout: Sair
  profile: Perfil
themes:
  labels:
    light: Luz
    dark: Escuro
