template:
  title: Segurança
  password:
    title: Senha
    change-link: Alterar sua senha
  mfa:
    title: Autenticação de múltiplos fatores
    totp:
      configure: Configurar
      enable: Habilitar
      disable: Desabilitar
    email:
      enable: Habilitar
      disable: Desabilitar
    all-disabled: Todos os métodos de autenticação de múltiplos fatores estão desabilitados. Contate o administrador para habilitá-los.
