automation:
  add: Добавить script
  edit:
    asyncHelp: Не ждите результатов и игнорируйте ошибки. Несовместимо с критическим флагом.
    asyncLabel: script выполняется асинхронно
    codeTabLabel: Код
    criticalHelp: Дождитесь выполнения этого сценария. В случае ошибок завершите выполнение других сценариев и до* триггера
    criticalLabel: Критический script
    delete: Удалить script
    enabledHelp: Отключенные скрипты будут игнорироваться
    enabledLabel: Отключено
    mailAutomationTriggers:
      addMatcher: Добавить условие
      addTrigger: Добавить триггер
      delete: Удалить триггер
      deleteTrigger: Удалить
      enable: Отключить триггер
      matchAll: Должны соответствовать всем условиям
      matcher:
        fields:
          bcc: BCC
          cc: CC
          from: From
          placeholder: Поле заголовка почты
          replyTo: Ответить на
          subject: Тема
          to: К
        match: Соответствующее значение
        operators:
          equal-ci: Полное совпадение
          placeholder: Оператор
          prefix-ci: Префикс совпадения
          regex: Регулярное выражение
          suffix-ci: Суффикс совпадения
          user: Существующий пользователь
      tabLabel: Почтовый триггер
    nameLabel: Имя
    namePlaceholder: Автоматизация script name
    runAsCurrentUser: Выполнить от "{{ user }}"
    runAsHelp: Script runner
    scheduledTriggers:
      tabLabel: Запланированный
    securityLabel: Безопасность
    settingsTabLabel: Настройки
    timeoutHelp: Сколько времени мы ждем, прежде чем прервать работу скрипта? Значение в миллисекундах (1000ms = 1s). По умолчанию (0) - 2s с максимальным значением 30 с. Проконсультироваться (...)
    timeoutLabel: Время ожидания выполнения скрипта
    timeoutPlaceholder: "1500"
    title: Automation script
    userPickerPlaceholder: Выберете user
  import: Импортировать скрипты автоматизации
  list:
    column:
      label:
        async: Асинх
        critical: Критический
        enabled: Включено
        runAs: Запуск от имени
        runInUA: в браузере
    unnamed: ' (скрипт без имени)'
  manage: Управлять скриптами автоматизации ({{count}})
  manage-id-permissions: Управление разрешениями для этого сценария
  manage-wc-permissions: Управление разрешениями для всех сценариев
  newLabel: Создать новый скрипт
  newPlaceholder: Имя скрипта
  testing:
    load: Загрузить
    parametersHeadline: 'Parameters & payload:'
    resultsHeadline: 'Результат:'
    testInBrowser: Тест в браузере
    testInCorredor: Тест в приложении
  title: Список сценариев автоматизации
general:
  notFound: 'Не найден'
  loading: Загрузка
  label:
    "no": "Нет"
    submit: Применить
    "yes": "Да"
    selectOption: "Пожалуйста, выберите один из вариантов"
  logout: Выйти
  noAccess: У вас нет прав доступа к панели администратора
  pagination:
    next: Следующий
    prev: предыдущий
navigation:
  adminPanel: Административная панель
  automation: Автоматизация
  chart: Диаграммы
  configuration: Конфигурация
  help:
    documentation: Документация
    feedback: Обратная связь
    forum: Помощь
    version: 'Версия:'
  module: Модули
  more: Подробнее
  namespace: Пространство имен
  noPageTitle: Нет названия страницы
  page: Страницы
  publicPages: Публичная страница
  userSettings:
    changePassword: Смена пароля
    loggedInAs: Вы вошли как {{user}}
    logout: Выйти
    profile: Профиль
