editor:
  title: Задать настройки
  basic:
    attachments:
      max-size: Макс. размер (MB)
      page: Вложение
      record: Сохранить вложения
      type:
        description: 'Значения, разделенные ",". Пример: "text/plain,text/csv"'
        whitelist: Разрешенный тип файлов
    title: Основной
  ui:
    title: Пользовательский интерфейс
