dashboard: Панель отчетов
system:
  group: Система
  items:
    users: Пользователь
    actionlog: Журнал действий
    apigw: Интеграцилнный шлюз
    applications: Приложения
    authclients: Клиенты авторизации
    permissions: Разрешения
    queues: Очередь сообщений
    roles: Роль
    email: Настройки электронной почты
    stats: Статистика
    templates: Шаблоны
compose:
  group: Собрать
  items:
    automation: Автоматизация
    permissions: Разрешения
    settings: Настройки
automation:
  group: Автоматизация
  items:
    permissions: Разрешения
    scripts: Corredor Scripts
    sessions: Сессия
    workflows: Бизнес-процесс
federation:
  group: Federation
  items:
    nodes: Nodes
    permissions: Разрешения
ui:
  group: Пользовательский интерфейс
  items:
    settings: Настройки
