editor:
  info:
    createdAt: Создан
    createdBy: Создан
    delete: Удалить
    deletedAt: Удалить
    enabled: Включено
    id: ID
    name: Имя *
    title: Базовая информация
    undelete: Восстановить
    updatedAt: Возобновлять
  permissions: Разрешения
  title:
    create: Создать приложение
    edit: Изменить приложение
  unify:
    config:
      description: Конфигурация приложения (JSON)
      label: Конфигурация
    listed: Списки
    logo:
      label: Logo
      description: Логотип, используемый в селекторе приложений
      placeholder: Выберите логотип или бросьте его здесь...
      reset: Перезагрузка
    name:
      description: Имя, используемое в селекторе приложений
      label: Имя
    pinned: Закреплено
    title: App selector
    url:
      description: URL Приложения
      label: URL
list:
  columns:
    createdAt: Создать
    enabled: Включено
    name: Имя
    appListName: Имя выбора приложений
  export: Экспорт
  rows:
    filters:
      deleted: Удалить
  filterForm:
    deleted:
      label: Удалить приложение
    excluded:
      label: Without
    exclusive:
      label: Единственный
    inclusive:
      label: Включая
    query:
      label: Список фильтров приложений
      placeholder: Список имен приложений
  loading: Загрузить приложение
  numFound: '{{count}} приложение найдена'
  numFound_plural: '{{count}} приложения найдены'
  permissions: Разрешения
  title: Приложения
  yaml: YAML
  delete: Удалить
  undelete: Восстановить
