editor:
  title: Параметры пользовательского интерфейса
  corteza-studio:
    mainLogo:
      title: Главный логотип
      uploader:
        instructions: Нажмите или перетащите файлы логотипа, чтобы загрузить
        uploading: Загрузка главного логотипа
    iconLogo:
      title: Иконка логотипа
      uploader:
        instructions: Нажмите или перетащите иконку логотипа, чтобы загрузить
        uploading: Загрузка иконки логотипа
    tabs:
      general: Главный
      light: Светлая
      dark: Темная
    theme:
      variables:
        primary:
          label: Начальный
        secondary:
          label: Второй
        success:
          label: Успешно
        warning:
          label: Предупреждение
        danger:
          label: Внимание
        light:
          label: Светлая
  topbar:
    general: Главный
    help:
      title: Помощь
    profile:
      title: Профиль
    links:
      handle: Имя
      url: URL
