errors:
  invalidID: معرف خاطئ
  notAllowedToCreate: غير مسموح انشاء تطبيقات
  notAllowedToDelete: غير مسموح حذف هذا التطبيق
  notAllowedToManageFlag: غير مسموح التحكم بمعطيات التطبيقات
  notAllowedToManageFlagGlobal: غير مسموح التحكم بالمعطيات العامة للتطبيقات
  notAllowedToRead: غير مسموح قراءة هذا التطبيق
  notAllowedToSearch: غير مسموح البحث او عرض التطبيق
  notAllowedToUndelete: غير مسموح اعادة هذا التطبيق
  notAllowedToUpdate: غير مسموح تحديث هذا التطبيق
  notFound: التطبيق غير موجود
