template:
  title: Sécurité
  password:
    title: Mot de passe
    change-link: Changez votre mot de passe
  mfa:
    title: Authentification multi-facteurs
    totp:
      configure: Configurer
      enable: Activer
      disable: Désactiver
      enabled: Mot de passe à usage unique basé sur le temps activé
    email:
      enable: Activer
      disable: Désactiver
    all-disabled: Toutes les méthodes MFA sont actuellement désactivées. Demandez à votre administrateur de les activer.
