---
automation:
  add: Skript hinzufügen
  edit:
    asyncHelp: Warten Sie nicht auf Ergebnisse und ignorieren Sie Fehler. Nicht kompatibel mit kritischem Flag.
    asyncLabel: Dieses Skript asynchron ausführen
    codeTabLabel: Code
    criticalHelp: Wait until this script is executed. In case of errors, abort execution of other scripts and before* trigger
    criticalLabel: Kritisches Skript
    delete: Skript löschen
    enabledHelp: Deaktivierte Skripte werden ignoriert
    enabledLabel: Aktiviert
    mailAutomationTriggers:
      addMatcher: Bedingung hinzufügen
      addTrigger: Trigger hinzufügen
      delete: Trigger löschen
      deleteTrigger: Löschen
      enable: Trigger aktivieren
      matchAll: Muss alle Bedingungen erfüllen
      matcher:
        fields:
          bcc: BCC
          cc: CC
          from: Von
          placeholder: E-Mail-Kopfzeilenfeld
          replyTo: Antworten an
          subject: Betreff
          to: An
        match: Value to match
        operators:
          equal-ci: Match full
          placeholder: Operator
          prefix-ci: Match prefix
          regex: Regex
          suffix-ci: Match suffix
          user: Existierender Benutzer
      tabLabel: E-Mail Auslöser
    nameLabel: Name
    namePlaceholder: Automation script name
    runAsCurrentUser: Run as "{{ user }}"
    runAsHelp: Script runner
    scheduledTriggers:
      tabLabel: Scheduled
    securityLabel: Security
    settingsTabLabel: Einstellungen
    timeoutHelp: How much time do we wait before aborting the script? Value in milliseconds (1000ms = 1s). It defaults (when 0) to 2s with 30s as maximum. Consult with your administrator for exact numbers and limitations.
    timeoutLabel: Script execution timeout
    timeoutPlaceholder: "1500"
    title: Automation script
    userPickerPlaceholder: Select user
  import: Import automation script(s)
  list:
    column:
      label:
        async: Async.
        critical: Kritisch
        enabled: Aktiviert
        runAs: Run As
        runInUA: In browser
    unnamed: (Unnamed script)
  manage: Manage automation scripts ({{count}})
  manage-id-permissions: Berechtigungen für dieses Skript verwalten
  manage-wc-permissions: Berechtigungen für alle Skripte verwalten
  newLabel: Neues Skript anlegen
  newPlaceholder: Script name
  testing:
    load: Load
    parametersHeadline: 'Parameters & payload:'
    resultsHeadline: 'Results:'
    testInBrowser: Test in Browser
    testInCorredor: Test in Corredor
    warning: ""
  title: List of automation script
general:
  notFound: 'Not found'
  label:
    "no": "Nein"
    submit: Submit
    "yes": "Yes"
  logout: Logout
  noAccess: You do not have permissions to access Admin panel
  pagination:
    next: Nächste
    prev: Prev
navigation:
  adminPanel: Admin Panel
  automation: Automation
  chart: Graphen
  configuration: Configuration
  help:
    documentation: Documentation
    feedback: Send feedback
    forum: Help
    version: 'Version:'
  module: Module
  more: Mehr
  namespace: Namespaces
  noPageTitle: No page title
  page: Pages
  publicPages: Public pages
  userSettings:
    changePassword: Change password
    loggedInAs: Logged in as {{user}}
    logout: Logout
    profile: Profile
