automation:
  add: Skript hinzufügen
  edit:
    asyncHelp: Warten Sie nicht auf Ergebnisse und ignorieren Sie Fehler. Nicht kompatibel mit kritischem Flag.
    asyncLabel: Dieses Skript asynchron ausführen
    codeTabLabel: Code
    criticalHelp: Warten Sie, bis dieses Skript ausgeführt wird. Im Falle von Fehlern die Ausführung anderer Skripte abbrechen und vorher* auslösen.
    criticalLabel: Kritisches Skript
    delete: Skript löschen
    enabledHelp: Deaktivierte Skripte werden ignoriert
    enabledLabel: Aktiviert
    mailAutomationTriggers:
      addMatcher: Bedingung hinzufügen
      addTrigger: Trigger hinzufügen
      delete: Trigger löschen
      deleteTrigger: Löschen
      enable: Trigger aktivieren
      matchAll: Muss alle Bedingungen erfüllen
      matcher:
        fields:
          bcc: BCC
          cc: CC
          from: Von
          placeholder: E-Mail-Kopfzeilenfeld
          replyTo: Antworten an
          subject: Betreff
          to: An
        match: Entsprechender Wert für
        operators:
          equal-ci: Komplette Überdeckung
          placeholder: Operator
          prefix-ci: Übereinstimmungs-präfix
          regex: Regex
          suffix-ci: Übereinstimmungs-suffix
          user: Existierender Benutzer
      tabLabel: E-Mail Auslöser
    nameLabel: Name
    namePlaceholder: Name des Automatisierungsskripts
    runAsCurrentUser: Ausführen als "{{ user }}"
    runAsHelp: Skriptausführer
    scheduledTriggers:
      tabLabel: Geplant
    securityLabel: Sicherheit
    settingsTabLabel: Einstellungen
    timeoutHelp: Wie viel Zeit wird gewartet, bevor das Skript abgebrochen wird? Wert in Millisekunden (1000ms = 1s). Standardmäßig (bei 0) sind es 2s, maximal 30s. Erkundigen Sie sich bei Ihrem Administrator nach den genauen Zahlen und Beschränkungen.
    timeoutLabel: Zeitüberschreitung bei der Skriptausführung
    timeoutPlaceholder: "1500"
    title: Skript zur Automatisierung
    userPickerPlaceholder: Nutzer auswählen
  import: Automatisierungsskript(e) importieren
  list:
    column:
      label:
        async: Async.
        critical: Kritisch
        enabled: Aktiviert
        runAs: Ausführen als
        runInUA: Im Browser
    unnamed: (Ungenanntes Skript)
  manage: Automatisierungsskripte verwalten ({{count}})
  manage-id-permissions: Berechtigungen für dieses Skript verwalten
  manage-wc-permissions: Berechtigungen für alle Skripte verwalten
  newLabel: Neues Skript anlegen
  newPlaceholder: Scriptname
  testing:
    load: Laden
    parametersHeadline: 'Parameter & Payload:'
    resultsHeadline: 'Ergebnis:'
    testInBrowser: Testen im Browser
    testInCorredor: Test in Corredor
  title: Liste der Automatisierungsskripte
general:
  notFound: 'Nicht gefunden'
  loading: Lade
  label:
    "no": "Nein"
    submit: Absenden
    "yes": "Ja"
  logout: Abmelden
  noAccess: Du hast keine Berechtigung um auf das Admin Panel zuzugreifen
  pagination:
    next: Nächste
    prev: Prev
navigation:
  adminPanel: Admin Panel
  automation: Automatisierung
  chart: Graphen
  configuration: Konfiguration
  help:
    documentation: Dokumentation
    feedback: Feedback senden
    forum: Hilfe
    version: 'Version:'
  module: Module
  more: Mehr
  namespace: Namensraum
  noPageTitle: Kein Seitentitel
  page: Seiten
  publicPages: Öffentliche Seiten
  userSettings:
    changePassword: Passwort ändern
    loggedInAs: Angemeldet als {{user}}
    logout: Abmelden
    profile: Profil
