editor:
  info:
    createdAt: Erstellt am
    createdBy: Erstellt bei
    delete: Löschen
    deletedAt: Gelöscht am
    enabled: Aktiviert
    id: ID
    name: Name
    title: Grundlegende Informationen
    undelete: Wiederherstellen
    updatedAt: Aktualisiert am
  new: New
  permissions: Berechtigungen
  unify:
    config:
      label: Konfiguration
    logo:
      label: Logo
      reset: Reset
    name:
      label: Name
    title: Unify app selector
    url:
      label: Location
list:
  columns:
    createdAt: Erstellt
    enabled: Aktiviert
    name: Name
  export: Exportieren
  rows:
    filters:
      deleted: Gelöscht
  filterForm:
    excluded:
      label: Ohne
    exclusive:
      label: Nur
    inclusive:
      label: Einschließlich
  new: New
  permissions: Berechtigungen
  title: Applications
  yaml: YAML
  delete: Löschen
  undelete: Wiederherstellen
