---
editor:
  info:
    createdAt: Erstellt am
    delete: Delete
    deletedAt: Gelöscht am
    enabled: Aktiviert
    id: ID
    name: Name
    title: Grundlegende Informationen
    undelete: Undelete
    updatedAt: Updated at
  new: Neu
  permissions: Permissions
  title:
    create: Create application
    edit: Edit application
  unify:
    config:
      description: Application configuration (JSON)
      label: Configuration
    listed: Listed
    logo:
      description: Logo used in the application selector
      label: Logo
      placeholder: Choose a logo or drop it here...
    name:
      description: Name used in the application selector
      label: Name
    pinned: Pinned
    title: App selector
    url:
      description: Application URL
      label: URL
list:
  columns:
    actions: ""
    createdAt: Erstellt
    enabled: Aktiviert
    name: Name
    appListName: App selector name
  filterForm:
    deleted:
      label: deleted applications
    excluded:
      label: Without
    exclusive:
      label: Nur
    inclusive:
      label: Including
    query:
      label: Filter applications list
      placeholder: Filter applications by name
  loading: Loading applications
  new: Neu
  numFound: '{{count}} application found'
  numFound_plural: '{{count}} applications found'
  permissions: Permissions
  title: Applications
  yaml: YAML
