editor:
  title: Einstellungen der Benutzeroberfläche
  corteza-studio:
    mainLogo:
      title: Hauptlogo
    iconLogo:
      title: Icon-Logo
    tabs:
      general: Allgemeines
      light: Hell
      dark: Dunkel
    theme:
      variables:
        primary:
          label: Primär
        secondary:
          label: Sekundär
        success:
          label: Erfolgreich
        warning:
          label: Warning
        danger:
          label: Gefährlich
        light:
          label: Hell
  topbar:
    general: Allgemeines
    help:
      title: Hilfe
    profile:
      title: Profil
    links:
      handle: Name
      url: Location
