editor:
  title: اعدادات النظام
  auth:
    title: المصادقة
    url: URL
    internal:
      title: داخلي
      enabled: تم تفعيل المصادقة الداخلية
      password-reset:
        enabled: تم تفعيل إعادة تعيين كلمة المرور
      password-constraints:
        title: قيود كلمة المرور
        ignored-security: تم تكوين النظام لتجاهل قيود أمان كلمات المرور غير الآمنة في عمليات نشر الإنتاج. إذا كان هذا نشر إنتاج ، فالرجاء الاتصال بالمسؤول لتحديث تكوين النظام (متغير AUTH_PASSWORD_SECURITY .env).
        min-length: الطول الأدنى
        min-length-description: يجب ألا يقل عن 8 أحرف
        min-special-count: الحد الأدنى لعدد الأحرف الخاصة
        min-special-count-description: يجب أن تتضمن كلمة المرور العدد المحدد من الأحرف الخاصة (معطل إذا تم ضبطه على 0)
      signup:
        email-confirmation-required: مطلوب تأكيد البريد الإلكتروني للتسجيل
        enabled: تمكين التسجيل
        split-credentials-check:
          description: 'قم بتقسيم تسجيل الدخول إلى خطوتين: جمع إدخال البريد الإلكتروني أولاً وإظهار إدخال كلمة المرور على الشاشة الثانية. قم بإعادة توجيه المستخدم تلقائيًا إلى موفر هوية خارجي عندما لا يتم تعيين كلمة مرور المستخدم الخاصة به ولا يوجد سوى IdP واحد موجود'
          label: Enable split-credentials check
      send-user-invite-email:
        expires:
          label: صالحة ل
    mail:
      title: بريد مرسل مصادقة البريد الإلكتروني
      from-address: عنوان المرسل
      from-name: اسم المرسل
      validate-email: الرجاء إدخال عنوان بريد إلكتروني صالح
    mfa:
      title: التحقق الثنائي
      TOTP:
        enabled: السماح للمستخدمين باستخدام كلمة مرور لمرة واحدة تستند إلى الوقت (باستخدام تطبيق الهاتف المحمول)
        enforced: إجبار المستخدمين على استخدام كلمة مرور لمرة واحدة تستند إلى الوقت (باستخدام تطبيق الهاتف المحمول)
        issuer:
          description: سيتم إرسال اسم المُصدر إلى تطبيق المصادقة عندما يقوم المستخدم بتكوينه
          label: المُصدر
      emailOTP:
        enabled: اسمح للمستخدمين باستخدام كلمة مرور لمرة واحدة عبر البريد الإلكتروني
        enforced: اسمح للمستخدمين باستخدام كلمة مرور لمرة واحدة عبر البريد الإلكتروني
        expires:
          description: كم من الوقت ستكون كلمة المرور صالحة قبل انتهاء صلاحيتها
          label: صالحة ل
    auto-logout:
      enabled:
        label: مفعل
  external:
    title: موفرو المصادقة الخارجية
    enabled: قم بتمكين المصادقة الخارجية
    table:
      header:
        enabled: مفعل
        provider: مزود
        info: المُصدر ، معرف العميل
    standard:
      enabled: مفعل
      clientKey: Client key
      clientSecret: سر
    oidc:
      add: أضف مزود OIDC
      enabled: مفعل
      handle: المعرف
      title: OpenID Connect
      issuer: عنوان URL لجهة إصدار OIDC
      issuerHint: أين يمكن العثور على /.well-known/openid-configuration (بدون جزء /.well-known/openid-configuration)
      clientKey: Client key
      clientSecret: سر
      scope: نطاق
      scopePlaceholder: سرد قيم نطاق OAuth المدعومة
      scopeHint: استخدم سلسلة محددة بمسافة
    saml:
      enabled: مفعل
      title: SAML
      requests:
        title: الطلبات
        sign-requests: طلبات التوقيع
        sign-method: طريقة التوقيع
        binding: ربط
        binding-redirect: HTTP Redirect
        binding-post: HTTP POST
      cert:
        public: Public key
        private: Private key
      name: اسم
      certificate: Certificate
      idp:
        title: Identity provider
        ident-handle: Handle field
        ident-identifier: Identifier field
        ident-name: Name field
        url: URL
      desc:
        name: اسم IdP المستخدم على شاشة تسجيل الدخول (تسجيل الدخول باستخدام <name>)
        cert:
          public: سيتم تصغير المحتوى
          private: سيتم تصغير المحتوى
        requests:
          sign-requests: Sign AuthNRequest and assertion
          sign-method: طريقة الاستخدام في الطلبات الموقعة
          binding: نوع ربط HTTP المراد استخدامه في AuthNRequest ، يتم تعيينه افتراضيًا على إعادة توجيه HTTP (GET)
        idp:
          url: Location of IdP metadata
          ident-handle: اسم حقل IdP المستخدم لملء اسم مستخدم Corteza أو لقبه
          ident-identifier: اسم حقل IdP المستخدم لملء البريد الإلكتروني لمستخدم Corteza ومطابقته
          ident-name: اسم حقل IdP المستخدم لملء الاسم الكامل لمستخدم Corteza
    security:
      title: الأمان
      prohibited-roles:
        description: ستتم إزالة الأدوار من هذه القائمة من سياق الأمان عند المصادقة مع هذا الموفر
      forced-roles:
        description: ستتم إضافة الأدوار من هذه القائمة دائمًا إلى سياق الأمان عند المصادقة مع هذا الموفر
        label: الأدوار القسرية
      permitted-roles:
        description: ستتم إضافة الأدوار الموجودة في هذه القائمة فقط إلى سياق الأمان عند المصادقة مع هذا الموفر
        label: الأدوار المسموح بها
