editor:
  info:
    createdAt: تم انشائه في
    createdBy: انشأ من قبل
    delete: حذف
    deletedAt: محذوف في
    enabled: مفعل
    id: ID
    name: اسم *
    title: معلومات مبدئية
    undelete: استعادة
    updatedAt: تم تحديثه في
  permissions: الصلاحيات
  title:
    create: إنشاء تطبيق جديد
    edit: تحرير تطبيق
  unify:
    config:
      description: Application configuration (JSON)
      label: اعدادات
    listed: مدرج
    logo:
      label: شعار
      description: الشعار المستخدم في محدد التطبيق
      placeholder: اختر شعارًا أو أسقطه هنا...
      reset: اعادة تعيين
    name:
      description: الاسم المستخدم في محدد التطبيق
      label: اسم
    pinned: مثبت
    title: محدد التطبيق
    url:
      description: Application URL
      label: URL
list:
  columns:
    createdAt: تم انشائه
    enabled: مفعل
    name: اسم
    appListName: محدد التطبيق
  export: تصدير
  rows:
    filters:
      deleted: محذوف
  filterForm:
    deleted:
      label: التطبيقات المحذوف
    excluded:
      label: بدون
    exclusive:
      label: فقط
    inclusive:
      label: يشمل
    query:
      label: قائمة التطبيقات المرشحة
      placeholder: قائمة التطبيقات المرشحة بالاسم
  loading: تحميل التطبيقات
  numFound: '{{count}} تطبيق'
  numFound_plural: '{{count}} تطبيقات'
  permissions: الصلاحيات
  title: التطبيقات
  yaml: YAML
  delete: حذف
  undelete: استعادة
