editor:
  title: إعدادات واجهة المستخدم
  corteza-studio:
    mainLogo:
      title: الشعار الرئيسي
      uploader:
        instructions: انقر أو أسقط الشعار الرئيسي هنا للتحميل
        uploading: تحميل الشعار الرئيسي
    iconLogo:
      title: أيقونة الشعار
      uploader:
        instructions: انقر أو أسقط صورة شعار الأيقونة هنا للتحميل
        uploading: رفع الشعار
    label:
      default: افتراضي
    tabs:
      general: عام
      light: فاتح
      dark: غامق
    theme:
      variables:
        primary:
          label: اساسي
        secondary:
          label: ثانوي
        success:
          label: ناجح
        warning:
          label: تنبيه
        danger:
          label: خطر
        light:
          label: فاتح
  topbar:
    general: عام
    help:
      title: مساعدة
    profile:
      title: الملف الشخصي
    links:
      handle: اسم
      url: URL
