colorLabel: '{{count}} couleurs'
colorScheme:
  label: Palette de couleurs
  placeholder: Choisissez une palette de couleurs
  pickAColor: Choisissez une couleur
  custom:
    add: Ajouter palette de couleurs
    edit: Éditer palette de couleurs
    modal:
      name:
        label: Nom
      colors:
        label: Couleurs
configure:
  reportsLabel: Rapports
general:
  label:
    title: Étiquette
    add: Ajouter
    count: Compte
    permissions: Permissions
  value: Valeur
  placeholder:
    name: 'Nom (exemple : "Ventes par mois")'
    handle: Identifiant unique (a - z, 0 - 9, tiret du bas, tiret)
    invalid-handle-characters: Doit contenir au moins 2 caractères. Ne peut contenir que des lettres, nombres, tirets bas et tirets. Doit se terminer avec une lettre ou un nombre
edit:
  animation:
    label: Animation
    enabled: Animation activée
  dimension:
    calculateLabelCount: Calculer combien d'étiquettes peuvent être affichées
    defaultValueFootnote: Utilisez cette valeur pour les valeurs de dimension manquantes
    defaultValueLabel: Valeur par défaut
    fieldLabel: Champ *
    fieldPlaceholder: Sélectionnez un champ de dimension
    function:
      placeholder: Sélectionnez le modificateur de dimension (taille de l'intervalle)
      none: Aucun groupement
      auto: Auto
      date: Date
      label: Fonction
      month: Mois
      quarter: Trimestre
      week: Semaine
      year: Année
    gaugeSteps: Étapes
    label: Dimensions
    skipMissingValues: Ignorer valeurs manquantes
    timeLabels: Étiquettes de temps
    options:
      label: Options
    optionsPicker:
      searchPlaceholder: Tapez ici pour rechercher parmi les options sélectionnées
      availableItems: Options disponibles
      selectAllItems: Sélectionner tout
      selectedItems: Options sélectionnées
      unselectAllItems: Désélectionner tout
      noItemsFound: Aucune option trouvée
    rotate:
      label: Pivoter étiquettes
      description: Les étiquettes peuvent être pivotées entre -90 et 90 degrés.
  filter:
    customize: Personnaliser filtre
    label: Filtrer
    preset: Filtres prédéfinis
    footnote: Les syntaxes conditionnelles SQL simplifiées (WHERE ...) sont prises en charge. Les variables tels que {{0}}, {{1}}, {{2}} et {{3}} sont évaluées (lorsque disponible)
    placeholder: champ1 = 1 AND champ2 = 232
    noFilter: Sélectionnez un filtre
    recordsCreatedLastMonth: Éléments créés le mois dernier
    recordsCreatedLastQuarter: Éléments créés le trimestre dernier
    recordsCreatedLastYear: Éléments créés l'année dernière
    recordsCreatedThisMonth: Éléments créés ce mois
    recordsCreatedThisQuarter: Éléments créés ce trimestre
    recordsCreatedThisYear: Éléments créés cette année
  loadData: Charger les données
  metric:
    title: Métriques
    add: Ajouter une métrique
    fieldLabel: Champ *
    fieldPlaceholder: Sélectionnez champ de la métrique
    fillArea: Remplir la zone sous la ligne
    fixTooltips: Toujours afficher étiquettes
    options:
      label: Options
    function:
      avg: MOY
      label: Fonction
      max: MAX
      min: MIN
      placeholder: Sélectionner la fonction d'agrégation de la métrique
      std: ET
      sum: SOM
    fx:
      description: n - valeur actuelle de l'ensemble de données, m - valeur précédente de l'ensemble de données
      label: Fonction de post-traitement
    stack:
      label: Pile
      description: Les métriques de même valeur seront empilées
    lineStyle:
      label: Style de ligne
      default: Défaut
      smooth: Lisse
      step: Étape
    angle:
      start: Angle de départ
      end: Angle de fin
    rose: Graphique polaire
    radar:
      shape:
        label: Forme de radar
        polygon: Polygone
        circle: Cercle
    gaugeColor: Couleur
    label: Métrique
    labelColor: Couleur d'étiquette
    labelLabel: Étiquette
    labelPlaceholder: Total
    symbol:
      label: Symbole
      circle: Cercle
      triangle: Triangle
      diamond: Diamant
      pin: Épingle
      arrow: Flèche
      rect: Rectangle
      roundRect: Rectangle arrondi
    legend:
      bottom: Bas
      left: Gauche
      positionPlaceholder: Position de la légende
      right: Droite
      top: Haut
    lineTension:
      curvy: Grandes courbures
      label: Tension de la ligne
      medium: Moyennes courbures
      placeholder: Tension de la ligne
      slight: Petites courbures
      straight: Lignes droites
    output:
      bar: Barre
      doughnut: Anneau
      label: Type de graphique
      line: Linéaire
      pie: Secteur
      scatter: Nuage de points
      placeholder: Sélectionnez le rendu de la métrique
    relative: Afficher valeur relative
    relativePrecision: 'Précision :'
    cumulative: Cumulatif
  module:
    label: Module *
    placeholder: Choisissez un module
    title: Source de données
  title: Constructeur de graphique
  unconfiguredReport: Rapport non configuré
  yAxis:
    axisOnRight: Placer axes sur le côté de droite
    axisScaleFromZero: Toujours débuter l'échelle de l'axe à zéro
    label: Axe Y
    options:
      label: Options
    rotate:
      label: Pivoter étiquettes
      description: Les étiquettes peuvent être pivotées entre -90 et 90 degrés
    labelLabel: Étiquette de l'axe
    labelPosition:
      label: Position de l'étiquette
      top: Début
      center: Centre
      bottom: Fin
    horizontal:
      label: Horizontal
    logarithmicScale: Échelle logarithmique
    maxLabel: Valeur maximale
    maxPlaceholder: Valeur maximale
    minLabel: Valeur minimum
    minPlaceholder: Valeur minimale
  additionalConfig:
    legend:
      label: Légende
      show: Afficher légende
      orientation:
        label: Orientation
        horizontal: Horizontal
        vertical: Vertical
      align:
        label: Alignement
        left: Gauche
        right: Droite
        center: Centre
      scrollable: Défilable
      position:
        customize: Position par défaut
        top: Haut
        right: Droite
        bottom: Bas
        left: Gauche
      valueRange: Les valeurs peuvent être définies en pixels 20 ou en pourcentages 20 %
      options:
        label: Options
    tooltip:
      label: Info-bulle
      labelNextToChart: Afficher étiquettes à côté du graphique
      formatting:
        label: Formatage personnalisé
        description: '{a} - étiquette de la métrique, {b} - valeur de dimension, {c} - valeur de la métrique, {d} - pourcentage de la valeur de la métrique'
        placeholder: '{a}<br />{b} : {c} ({d}%)'
        disclaimer: L'ajout d'une valeur au champ de formatage désactivera le format numérique, préfixe et suffixe des champs et inversement
    offset:
      label: Décalage
      default: Décalage par défaut
      position:
        top: Haut
        right: Droite
        bottom: Bas
        left: Gauche
      valueRange: Les valeurs peuvent être définies en pixels 20 ou en pourcentages 20 %
  toolbox:
    label: Outils
    saveAsImage:
      label: Afficher bouton "Enregistrer comme image"
    timeline:
      label: Chronologie
      options:
        none: Aucune
        x: Axe X
        y: Axe Y
        xy: Les deux
  formatting:
    format:
      label: Format
      placeholder: '0.00'
    prefix:
      label: Préfixe
      placeholder: '#'
    suffix:
      label: Suffixe
      placeholder: '€'
    presetFormats:
      label: Format
      options:
        custom: Personnalisé
        accounting: Nombre comptable
      description:
        accounting: Les nombres négatifs sont transformés en positifs puis placé entre parenthèses, la valeur 0 est remplacé par un tiret
import: 'Import de graphique(s) :'
newLabel: 'Créer un nouveau graphique :'
name: Nom de graphique *
handle: Identifiant
generalSettings: Paramètres généraux
notification:
  loadFailed: Impossible de charger le graphique
  saveFailed: Impossible d'enregistrer ce graphique
  saved: Graphique enregistré
  deleteFailed: Impossible de supprimer ce graphique
  deleted: Graphique supprimée
searchPlaceholder: Rechercher graphiques dans ce namespace
title: Liste des graphiques
undefined: Non défini
